import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import Link from "next/link";

// import ClientOnly from "@/components/ClientOnly";
// import Modal from "@/components/modals/Modal";
//import icon
import { BsBookmarkFill } from "react-icons/bs";
import { IoSettingsSharp } from "react-icons/io5";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface PlazaLayoutProps {
  children: React.ReactNode;
}

export default function PlazaLayout({ children }: PlazaLayoutProps) {
  return (
    <div className="container mx-auto flex h-full px-20 pt-32">
      <div className=" w-3/12 ">
        <div className="flex flex-col rounded-md border-2 border-blue-400 p-3 ">
          <Button variant="ghost" asChild className="my-1 justify-start ">
            <Link href="/explore">
              <BsBookmarkFill className=" text-red-400" size={24} />
              探索
            </Link>
          </Button>
          <Button variant="ghost" asChild className="my-1 justify-start ">
            <Link href="/bookmarks">
              <BsBookmarkFill className=" text-red-400" size={24} />
              收藏
            </Link>
          </Button>
          <Button variant="ghost" asChild className="my-1 justify-start ">
            <Link href="/profile">
              <BsBookmarkFill className=" text-red-400" size={24} />
              個人檔案
            </Link>
          </Button>
          <Button variant="ghost" asChild className="my-1 justify-start ">
            <Link href="/settings">
              <IoSettingsSharp className=" text-red-400" size={24} />
              設定
            </Link>
          </Button>
        </div>
      </div>
      <div className=" h-full w-9/12 bg-purple-400">{children}</div>
    </div>
  );
}
